# Observations

We have collected loss observations for the 2024 Porto Alegre floods from different sources. These will be used to calibrate the model.

The observations contain different measures of impact: both affected and financial impact.

In [3]:
from pathlib import Path

# -----------------------------------------------
# Set up paths to data
# -----------------------------------------------

OBSERVATIONS_DIR = "../data/observations/"
OBSERVATIONS_FILE = "observations_2024.csv"
observations_filepath = Path(OBSERVATIONS_DIR) / OBSERVATIONS_FILE

In [6]:
import pandas as pd
import numpy as np
from IPython.display import display

# -----------------------------------------------
# Read and print the observations
# -----------------------------------------------

obs = pd.read_csv(observations_filepath)

print("Observations: affected")
obs_affected = obs[obs['Impact type'] == 'Affected']
display(obs_affected)

print("Observations: economic loss")
obs_loss = obs[obs['Impact type'] == 'Economic loss']
display(obs_loss)

Observations: affected

,Asset type,Impact type,Units,Value,Note,Source,URL
0,Residential,Affected,Buildings,"39,422",NaN,Porto Alegre,https://gis-smamus.portoalegre.rs.gov.br/porta...
1,Schools,Affected,Schools,160,NaN,Porto Alegre,https://gis-smamus.portoalegre.rs.gov.br/porta...
2,Business: All,Affected,Businesses,"65,528","Sum of Commercial, Industrial, Tourism & Resta...",Porto Alegre,https://gis-smamus.portoalegre.rs.gov.br/porta...
3,Business: Commercial,Affected,Businesses,"18,994",NaN,Porto Alegre,https://gis-smamus.portoalegre.rs.gov.br/porta...
4,Business: Industrial,Affected,Businesses,"6,442",NaN,Porto Alegre,https://gis-smamus.portoalegre.rs.gov.br/porta...
5,Business: Tourism & Restaurants,Affected,Businesses,"7,628",NaN,Porto Alegre,https://gis-smamus.portoalegre.rs.gov.br/porta...
6,Business: Other,Affected,Businesses,"32,464",NaN,Porto Alegre,https://gis-smamus.portoalegre.rs.gov.br/porta...

Observations: economic loss

,Asset type,Impact type,Units,Value,Note,Source,URL
7,Residential,Economic loss,R$,"1,178,726,000",NaN,IDB,https://publications.iadb.org/pt/avaliacao-dos...
8,Schools,Economic loss,R$,"677,043,000",NaN,IDB,https://publications.iadb.org/pt/avaliacao-dos...
9,Business: All,Economic loss,R$,"2,437,530,000","Sum of Commercial, Industrial, Tourism & Resta...",IDB,https://publications.iadb.org/pt/avaliacao-dos...
10,Business: Commercial,Economic loss,R$,"1,345,280,000",NaN,IDB,https://publications.iadb.org/pt/avaliacao-dos...
11,Business: Industrial,Economic loss,R$,"792,403,000",NaN,IDB,https://publications.iadb.org/pt/avaliacao-dos...
12,Business: Tourism & Restaurants / Service,Economic loss,R$,"299,847,000",NaN,IDB,https://publications.iadb.org/pt/avaliacao-dos...